---
Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../crypto-config/ordererOrganizations/synergy.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &InvestorOrg
    Name: InvestorOrgMSP
    ID: InvestorOrgMSP
    MSPDir: ../crypto-config/peerOrganizations/investororg.synergy.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('InvestorOrgMSP.admin', 'InvestorOrgMSP.peer', 'InvestorOrgMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('InvestorOrgMSP.admin', 'InvestorOrgMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('InvestorOrgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('InvestorOrgMSP.peer')"
    AnchorPeers:
      - Host: peer0.investororg.synergy.com
        Port: 7051

  - &UmkmOrg
    Name: UmkmOrgMSP
    ID: UmkmOrgMSP
    MSPDir: ../crypto-config/peerOrganizations/umkmorg.synergy.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('UmkmOrgMSP.admin', 'UmkmOrgMSP.peer', 'UmkmOrgMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('UmkmOrgMSP.admin', 'UmkmOrgMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('UmkmOrgMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('UmkmOrgMSP.peer')"
    AnchorPeers:
      - Host: peer0.umkmorg.synergy.com
        Port: 9051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.synergy.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.synergy.com
        Port: 7050
        ClientTLSCert: ../crypto-config/ordererOrganizations/synergy.com/orderers/orderer.synergy.com/tls/server.crt
        ServerTLSCert: ../crypto-config/ordererOrganizations/synergy.com/orderers/orderer.synergy.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  SynergyGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SynergyConsortium:
        Organizations:
          - *InvestorOrg
          - *UmkmOrg

  SynergyChannel:
    Consortium: SynergyConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *InvestorOrg
        - *UmkmOrg
